Replicator: Add support to insert and update non-frozen UDTs
piodul/scylla-cdc-rust pull request #47
Opened 2022-03-07 23:12 UTC by Gor027

Fixes #22
The PR adds support for inserting and updating non-frozen User Defined Type (UDT) columns.
Also includes small polishing to avoid `cargo clippy` warnings.

2022-03-08 17:20 UTC, Gor027 commented on scylla-cdc-replicator/src/replication_tests.rs
> +            })
Well, I have tried to shorten the nested matches by using `match (o, r)`, but in that case when it tries to match both to be `UserDefinedType` values, there happened naming collision on `fields`, and I could not find a way to assign them different names to use them in the matching block.

2022-03-08 18:21 UTC, piodul commented on scylla-cdc-replicator/src/replication_tests.rs
> +            })
> I could not find a way to assign them different names to use them in the matching block.

You can do it like this:

```rust
match (o, r) {
    (
        CqlValue::UserDefinedType { fields: original_fields, .. },
        CqlValue::UserDefinedType { fields: replicated_fields, .. },
    ) => {
        /* ... */
    }
}
```

Ref: https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#destructuring-structs

2022-03-11 09:43 UTC, piodul commented on scylla-cdc-replicator/src/replication_tests.rs
>          operations: Vec<TestOperation<'_>>,
You fixed this in the wrong commit. The first commit still shows duplicated code.

2022-03-11 10:38 UTC, piodul approved these changes

2022-03-11 10:41 UTC, piodul requested changes

2022-03-11 10:41 UTC, piodul commented on scylla-cdc-replicator/src/replication_tests.rs
> +    async fn test_udt_update() {
This is not marked as a test and it does not run in CI.

2022-03-11 10:41 UTC, piodul commented on scylla-cdc-replicator/src/replication_tests.rs
> +    async fn test_udt_fields_update() {
This is not marked as a test.

2022-03-11 11:29 UTC, piodul approved these changes

2022-03-11 11:29 UTC, merged