#74 Fix UDT replication fail
piodul/scylla-cdc-rust pull request #79
Opened 2022-04-28 11:33 UTC by Ponewor

Resolves #74

2022-04-28 14:53 UTC, Ponewor commented
@piodul

2022-04-28 16:07 UTC, piodul requested changes

2022-05-02 05:38 UTC, piodul requested changes

2022-05-02 05:38 UTC, piodul commented on scylla-cdc-replicator/src/replicator_consumer.rs
> +        let value = data.get_value(column_name).as_ref().unwrap();
The `test_udt_fields_update` test fails when I add another column and try to update it.

```diff
@@ -848,7 +848,7 @@ mod tests {
             name: "TEST_UDT_ELEMENTS_UPDATE".to_string(),
             partition_key: vec![("pk", "int")],
             clustering_key: vec![("ck", "int")],
-            other_columns: vec![("v", "ut")],
+            other_columns: vec![("v", "ut"), ("dummy", "int")],
         };
 
         let udt_schemas = vec![TestUDTSchema {
@@ -864,6 +864,7 @@ mod tests {
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = null, v.bool_val = false WHERE pk = 0 AND ck = 1",
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = 5 WHERE pk = 0 AND ck = 1",
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = null WHERE pk = 0 AND ck = 1",
+            "UPDATE TEST_UDT_ELEMENTS_UPDATE SET dummy = 1 WHERE pk = 0 AND ck = 1",
         ];
 
         test_replication_with_udt(schema, udt_schemas, operations)
```
```
failures:

---- replication_tests::tests::test_udt_fields_update stdout ----
unique_name: test_rust_1651469149_7
unique_name: test_rust_1651469150_39
thread 'replication_tests::tests::test_udt_fields_update' panicked at 'called `Option::unwrap()` on a `None` value', scylla-cdc-replicator/src/replicator_consumer.rs:502:58
```

`cdc$deleted_x == false || cdc$deleted_x == null` does not imply that `x` column is not-null. If the column `x` was unaffected in the original operation, then both `x` and `cdc$deleted_x` will be null/false - so you can't just unwrap here.

2022-05-06 06:06 UTC, piodul approved these changes
Looks good, but I would appreciate a regression test against the issue with the logic not working properly when the column type was not updated in the operation. Let's follow up with a test which adds a table with multiple columns of different types and, in each operation, updates only one column.

2022-05-06 06:07 UTC, merged